### ISSUE TITLE
Moving files to parent folder gives error

### ISSUE THREAD

**Issue by woubuc** [andrewrk/node-mv#21]
I'm trying to move files from a subfolder to `process.cwd()` but when I try, it gives an `ENOTEMPTY` error.

```
{ [Error: ENOTEMPTY, rename '/Users/wouter/Dev/project-templates/project-template/bin/']
  errno: -66,
  code: 'ENOTEMPTY',
  path: '/Users/wouter/Dev/project-templates/project-template/bin/' }
```

It seems like it's trying to rename the cwd (as I'm testing the cli I'm working on in the `bin` folder directly). The same thing happens when I use `npm link` and test it in a newly created test directory.

@andrewrk am I missing a setting or something, or is this just not possible with `mv`?

**Comment by sigmasoldi3r** [comment]
+1 I get another error but is when trying to move a folder one level up (Like moving to `../`)

```
fs.js:310
  binding.stat(pathModule._makeLong(path), req);
          ^

TypeError: path must be a string or Buffer
    at Object.fs.exists (fs.js:310:11)
    at Object.destExists (...)
(...)/node_modules/node-mv/index.js:50:76
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
```

### Code

What is tested so far, is taken directly from examples:
```javascript
  /**
   * Moves the directory tree one level up.
   * @param {string} from
   * @returns {Promise}
   */
  __moveDirs (from) {
    return new Promise((resolve, reject) => {
      mv(from, this.__dest, (err) => {
        if (err) {
          reject(err);
        } else {
          resolve();
        }
      });
    });
  }
```
Where **this.__dest** is the parent of **from**

I'll try another solution in the meantime

**Comment by gigouni** [comment]
FYI, 

I was having this problem and solved it using another npm module, [copy-dir-cli](https://www.npmjs.com/package/copy-dir-cli). Simple but works great!
